import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "home": "الرئيسية",
          "Services": "الخدمات",
          "namik": "نامق",
          "map": "الخريطة",
          "account": "حسابي",
          "GPA": "الحاسبة",
          "GPA_1": "فصلي",
          "GPA_2": "تراكمي",
          "GPA_11": "حساب المعدل الفصلي",
          "GPA_22": "حساب المعدل التراكمي",
          "ph": "ادخل/ـي الساعات السابقة",
          "vi": "ادخل/ـي رقمًا",
          "pg": "أدخل/ـي المعدل السابق",
          "pa": "الرجاء إدخال مادة",
          "LN": "أدخل/ـي اسم المادة",
          "points": "النقاط",
          "rules": "القواعد",
          "rules_2": "خدمات و قوانين الجامعة",
          "serv": "خدمات الجامعة",
          "serv_2": " الخدمات المعروضة هي خدمات مقررة من الجامعة",
          "serv_st": "خطوات تنفيذ الخدمة:",
          "List": "قائمة",
          "Calendar": "التقويم",
          "Acadmic": "التقويم الأكاديمي",
          "more": "المزيد",
          "Name": "الاسم",
          "UID": "الرقم الجامعي",
          "info": "معلوماتي",
          "back": "العودة للخلف",
          "pass": "تغيير كلمة المرور",
          "new pass": "كلمة المرور الجديدة",
          "curr pass": "كلمة المرور الحالية",
          "ch pass": "تم تغيير كلمة المرور بنجاح",
          "ent pass": "يجب ان تكون كلمة المرور المدخلة متساوية ",
          "who": "من نحن",
          "out": "تسجيل الخروج",
          "fill": "يجب تعبئة هذا الحقل",
          "change e": "تغيير الايميل",
          "change n": "تغيير الاسم",
          "most": " @qu.edu.saيجب ان يكون الايميل الجامعي ينتهي بـ",
          "Save": "حفظ",
          "qmap": "خريطة جامعة القصيم",
          "forget": "؟نسيت كلمة المرور",
          "sign up": "تسجيل",
          "error": "حصل خطأ ما",
          "too weak": "كلمة مرور ضعيفة",
          "no user": "لا يوجد مستخدم يطابق الايميل",
          "no pass": "كلمة المرور لا تطابق المستخدم",
          "Nice": "أهلًا بك !",
          "Login": "تسجيل الدخول",
          "forge": "نسيت",
          "forgpage": "نسيان كلمة المرور",
          "forgpage1":
              "أدخل بريدك الإلكتروني لعملية التحقق، \nسنرسل  رمزًا مكونًا من أربعة أرقام الى بريدك الإلكتروني",
          "welcome": "مرحبًا بعودتك!",
          "wrong": "ايميل لا يطابق",
          "less": "طول كلمة المرور لا يمكن ان يكون اقل من 8",
          "conf": "تأكيد كلمة المرور",
          "account updated": "تم تحديث الحساب بنجاح",
          "Dacc": "ليس لديك حساب؟",
          "Lang": "اللغة",
          "ab":
              "خدمات الجامعة الأكاديمية متاحة للطلاب لمساعدتهم خلال رحلتهم الأكاديمية. يقضي المستشارون الأكاديميون الكثير من الوقت والجهد في مساعدة الطلاب على تحقيق أهدافهم الأكاديمية وتوضيح أي ارتباك. ومع ذلك، نظرًا لعبء عملهم الثقيل، قد لا يكون المستشارون الأكاديميون دائمًا قادرين على الرد على الطلاب بسرعة أو تزويدهم بمعلومات أفضل أو أكثر دقة. بالرغم من فوائدها، هناك حالات يمكن فيها أن يسبب مجموعة الخدمات وكمية المصادر مشاكل للطلاب الذين يبحثون عن المعلومات الصحيحة وينتهي بهم الأمر بالتشتت. يهدف هذا المشروع إلى توفير حل شامل للطلاب، يوفر جميع الموارد التي قد يحتاجها الطالب في رحلته الأكاديمية. يوفر المشروع خمس ميزات رئيسية: محادثة آلية، وكيل ذكي محادث، خريطة تفاعلية تعزز توجيه الحرم الجامعي بشكل عام، هوية رقمية تقدم وسيلة مريحة وآمنة للتحقق من الهوية، لوحة تحكم أكاديمية، تنبيه الطلاب بالأحداث الأكاديمية الحرجة، وتقديم خدمات أكاديمية مثل حساب متوسط التركيز وصفحة قواعد الجامعة. يطمح هذا المشروع إلى مساعدة في التخفيف من التحديات والصعوبات التي يواجهها طلاب جامعة قطر، وتشجيع نمو الطلاب الفكري وتحقيق النجاح الأكاديمي، وبالتالي تقليل العبء على المستشارين الأكاديميين وموظفي الجامعة في العملية.",
          "search": "إبحث",
          "hou": "الساعات",
          "send": "إرسال",
          "CL": "موقعك",
          "MO": "اختر/ي",
          "FR": "المسار",
          "DM": "حذف العلامة",
          "MS": "تم الحفظ",
          "MD": "تم حذف العلامة!",
        },
        "en": {
          "home": "home",
          "Services": "services",
          "namik": "namik",
          "Map": "map",
          "account": "profile",
          "GPA": "GPA",
          "GPA_1": "Semester",
          "GPA_2": "cumulative",
          "GPA_11": "Semester GPA calculation",
          "GPA_22": "Cumulative GPA calculation",
          "ph": "Enter The Previous Hours.",
          "vi": "Enter a valid number.",
          "pg": "Enter The Previous GPA",
          "pa": "Please Add Lesson.",
          "LN": "Enter The Lesson Name.",
          "points": "Points",
          "rules": "Rules",
          "rules_2": "University rules and services",
          "serv": "University services",
          "serv_2": "The offered services are mandated university services",
          "serv_st": "Steps to implement the service:",
          "List": "List",
          "Calendar": "Calendar",
          "Acadmic": "Acadmic Calendar",
          "more": "see more",
          "Name": "Name",
          "UID": "UID",
          "info": "My info",
          "back": "Go Back",
          "pass": "Change password",
          "new pass": "New password",
          "curr pass": "Current Password",
          "ch pass": "password changed successfully",
          "ent pass": "The entered password must be equal",
          "who": "Who we are",
          "out": "Log out",
          "fill": "you should fill this field.",
          "change e": "Change email",
          "change n": "Change name",
          "most": "must contains @qu.edu.sa",
          "Save": "Save",
          "qmap": "Qassim University Map",
          "forget": "forget password?",
          "forgpage": "Forget Password",
          "forgpage1":
              "Enter your email for the verification process, \nwe will send 4 digits code to your email.",
          "sign up": "sign up",
          "error": "error occurred",
          "too weak": "the password provided is too weak.",
          "no user": "no user found for that email.",
          "no pass": "wrong password provided for that user.",
          "Nice": "Nice to meet you!",
          "Login": "Login",
          "forge": "forget",
          "welcome": "Welcome Back!",
          "wrong": "wrong email!",
          "less": "not less than 8!",
          "conf": "Confirm Password",
          "account updated": "account updated successfully",
          "Dacc": "Don 't Have Account?",
          "Lang": "Language",
          "ab":
              "University academic services are provided to the student to help them during their academic jour- ney. Academic advisors spend a lot of time and effort helping students achieve their academic goals and clearing up any confusion. However, because of their heavy workload, academic advisors may not always be able to respond to students promptly or provide them with better or more accurate information. As beneficial as they are, there are situations when the range of services and quantity of sources may cause problems for students searching for the right information and wind up distracting them. this project aims to provide students with a one-stop solution, providing all the resources a student may need in their academic journey. the project specifically provides five main features:a Chatbot, a conversational smart agent, an Interactive map, enhancing overall campus orienta- tion, a Digital ID, offering a convenient and secure means of identity verification, an Academic dashboard, notifying students of critical academic events, and provides Academic services such as GPA calculation and University rules page. This project aspires to help alleviate the challenges and difficulties faced by QU students, and to encourage the students’ intellectual growth and aca- demic achievement, reducing the load on academic advisors and University staff in the process.",
          "search": "Search",
          "hou": "hours",
          "send": "send",
          "servpage": "Academic Services",
          "CL": "your location",
          "MO": "Marker Options",
          "FR": "Find Route",
          "DM": "Delete Marker!",
          "MS": "Marker saved!",
          "MD": "Marker deleted!"
        },
      };
}
