import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "home": "الصفحة الرئيسية",
          "Services": "الخدمات",
          "namik": "نامق",
          "map": "الخريطة",
          "account": "حسابي",
          "GPA": "الحاسبة",
          "GPA_1": "فصلي",
          "GPA_2": "تراكمي",
          "GPA_11": "حساب المعدل الفصلي",
          "GPA_22": "حساب المعدل التراكمي",
          "ph": "ادخل/ـي الساعات السابقة",
          "vi": "ادخل/ـي رقمًا",
          "pg": "أدخل/ـي المعدل السابق",
          "pa": "الرجاء إدخال مادة",
          "LN": "أدخل/ـي اسم المادة",
          "points": "النقاط",
          "rules": "القواعد",
          "rules_2": "خدمات و قوانين الجامعة",
          "serv": "خدمات الجامعة",
          "serv_2": " الخدمات المعروضة هي خدمات مقررة من الجامعة",
          "serv_st": "خطوات تنفيذ الخدمة:",
          "List": "قائمة",
          "Calendar": "التقويم",
          "Acadmic": "التقويم الأكاديمي",
          "more": "المزيد",
          "Name": "الاسم",
          "UID": "الرقم الجامعي",
          "info": "معلوماتي",
          "back": "العودة للخلف",
          "pass": "تغيير كلمة المرور",
          "new pass": "كلمة المرور الجديدة",
          "curr pass": "كلمة المرور الحالية",
          "ch pass": "تم تغيير كلمة المرور بنجاح",
          "ent pass": "يجب ان تكون كلمة المرور المدخلة متساوية ",
          "who": "من نحن",
          "out": "تسجيل الخروج",
          "fill": "يجب تعبئة هذا الحقل",
          "change e": "تغيير الايميل",
          "change n": "تغيير الاسم",
          "most": " @qu.edu.saيجب ان يكون الايميل الجامعي ينتهي بـ",
          "Save": "حفظ",
          "qmap": "خريطة جامعة القصيم",
          "forget": "نسيت كلمة المرور",
          "sign up": "تسجيل",
          "error": "حصل خطأ ما",
          "too weak": "كلمة مرور ضعيفة",
          "no user": "لا يوجد مستخدم يطابق الايميل",
          "no pass": "كلمة المرور لا تطابق المستخدم",
          "Nice": "سعدنا بلقائك",
          "Login": "تسجيل الدخول",
          "forge": "نسيت",
          "welcome": "مرحبًا بعودتك!",
          "wrong": "ايميل لا يطابق",
          "less": "طول كلمة المرور لا يمكن ان يكون اقل من 8",
          "conf": "تأكيد كلمة المرور",
          "account updated": "تم تحديث الحساب بنجاح",
          "Dacc": "ليس لديك حساب؟",
        },
        "en": {
          "home": "HOME",
          "Services": "Services",
          "namik": "namik",
          "Map": "Map",
          "account": "My Account",
          "GPA": "GPA",
          "GPA_1": "Semester",
          "GPA_2": "cumulative",
          "GPA_11": "Semester GPA calculation",
          "GPA_22": "Cumulative GPA calculation",
          "ph": "Enter The Previous Hours.",
          "vi": "Enter a valid number.",
          "pg": "Enter The Previous GPA",
          "pa": "Please Add Lesson.",
          "LN": "Enter The Lesson Name.",
          "points": "Points",
          "rules": "Rules",
          "rules_2": "University rules and services",
          "serv": "University services",
          "serv_2": "The offered services are mandated university services",
          "serv_st": "Steps to implement the service:",
          "List": "List",
          "Calendar": "Calendar",
          "Acadmic": "Acadmic Calendar",
          "more": "see more",
          "Name": "Name",
          "UID": "UID",
          "info": "My info",
          "back": "Go Back",
          "pass": "Change password",
          "new pass": "new password",
          "curr pass": "Current Password",
          "ch pass": "Password changed successfully",
          "ent pass": "The entered password must be equal",
          "who": "who we are",
          "out": "Log out",
          "fill": "You should fill this field.",
          "change e": "Change email",
          "change n": "Change name",
          "most": "must contains @qu.edu.sa",
          "Save": "Save",
          "qmap": "Qassim University map",
          "forget": "forget Password",
          "sign up": "Sign Up",
          "error": "error Occurred",
          "too weak": "The password provided is too weak.",
          "no user": "No user found for that email.",
          "no pass": "Wrong password provided for that user.",
          "Nice": "Nice To Meet you",
          "Login": "Login",
          "forge": "Forget",
          "welcome": "welcome Back!",
          "wrong": "Wrong email!",
          "less": "not less than 8!",
          "conf": "Confirm Password",
          "account updated": "account updated success",
          "Dacc": "Don 't Have Account?",
        },
      };
}
